# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03755af1100bdc03797566d6bbb498a56b4063d923afad23015706972ec857043c4d7a140bcae51482cb1c4af40c7dabc2ae4f3c49a2ba07dc1ec1908136b4d0

test:
  secret_key_base: f9068af10baa0016e45842040d52d7390db9bdaa500d59c988b260568adcb2d0492b537eabb8315767dd53ccdd12fc84dcdfa1c1bc4da3cb05bc2ca980724a0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
