tag_list_example:
  - 'Web Design'
  - 'UI'
  - 'Application'

s3:
  access_key: ENV['ACCESS_KEY_ID']
  secret_access_key: ENV['SECRET_ACCESS_KEY']
  region: 'us-east-1'
  fog_directory: 'protospace-yogoken'
  asset_host: 'https://s3.amazonaws.com/protospace-yogoken'
